baseURL = "https://blog.raphlcx.com"
languageCode = "en-gb"
title = "raphlcx"
theme = "blog"
rssLimit = 10
disableKinds = ["section", "taxonomy", "term"]

[taxonomies]
tag = "tags"

[params]
description = "Writing as technology maker, for technology makers"
